spring.application.name=todos

# Docker Setup
spring.datasource.url=jdbc:mysql://localhost:3307/tododb?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

springdoc.swagger-ui.path=/docs

spring.jwt.secret=55773ec63465f82b8c770a18c1006294b832dcd1b20f64e95a0078625ae4f6ea
spring.jwt.expiration=900000
